export const sidebarLinks = [
    {
      id: 1,
      title: "Dashboard",
      href: "/",
      alternateHref: "/",
    },
//     {
//       id: 2,
//       title: "Players",
//       href: "/agents",
//       alternateHref: "/add-users",
//     },
//     // {
//     //   id: 3,
//     //   title: "Add Players",
//     //   href: "/add-users",
//     //   alternateHref: "/add-users",
//     // },
//     {
//       id: 3,
//       title: "Income",
//       href: "/incomes",
//       alternateHref: "/incomes",
//     },
//     {
//       id: 4,
//       title: "Unsynced Incomes",
//       href: "/temp-incomes",
//       alternateHref: "/temp-incomes",
//     },
//     // {
//     //   id: 6,
//     //   title: "Synced Incomes",
//     //   href: "/synced-incomes",
//     //   alternateHref: "/synced-incomes",
//     // },
//     // {
//     //   id: 6,
//     //   title: "Synced Incomes",
//     //   href: "/synced-incomes",
//     //   alternateHref: "/synced-incomes",
//     // },
//     {
//       id: 5,
//       title: "Flushed",
//       href: "/flushed-incomes",
//       alternateHref: "/flushed-incomes",
//     },
//     {
//       id: 6,
//       title: "Withdrawals ",
//       href: "/transactions",
//       alternateHref: "/transactions",
//     },
//     {
//       id: 7,
//       title: "Gold Saffron Request",
//       href: "/player-requests",
//       alternateHref: "/player-requests",
//     },
//     {
//       id: 8,
//       title: "Gold Saffron Assigned",
//       href: "/agent-assign",
//       alternateHref: "/agent-assign",
//     },
//     {
//       id: 9,
//       title: "Support",
//       href: "/support",
//       alternateHref: "/support",
//     },
//     // {
//     //   id: 11,
//     //   title: "Send-Notification",
//     //   href: "/send-notification",
//     //   alternateHref: "/send-notification",
//     // },
//     {
//       id: 10,
//       title: "Notification",
//       href: "/notification",
//       alternateHref: "/send-notification",
//     },
//     {
//       id: 11,
//       title: "Update Password",
//       href: "/update-password",
//       alternateHref: "/update-password",
//     },
//     {
//       id: 12,
//       title: "Eligible for Saffron",
//       href: "/eligible-saffron",
//       alternateHref: "/eligible-daffron",
//     },
//     {
//       id: 13,
//       title: "Eligible for Gold",
//       href: "/eligible-gold",
//       alternateHref: "/eligible-gold",
//     },
  ];