import LeftBar from "@/components/shared/Leftbar";
import "../globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`$${inter.className} p-5 bg-purple-50 flex gap-4 w-full h-screen `}
      >
        <LeftBar/>
        <main className="w-full  ">{children}</main>
      </body>
    </html>
  );
}
